# Generated by Django 6.0 on 2026-03-17 11:10

from django.db import migrations

def add_stock_reports_permissions_version2(apps, schema_editor):
    from django.contrib.auth.models import Permission
    from django.contrib.contenttypes.models import ContentType

    content_type, _ = ContentType.objects.get_or_create(app_label='auth', model='user')

    permissions = [
        ('view_stock_reports_page', 'Can view Stock reports page'),
        ('view_stock_worth_report', 'Can see stock worth report'),
        ('view_item_detail', 'Can see particular item detail'),
        ('view_last_purchasing', 'Can see last purchasing of all items'),
        ('view_last_sale', 'Can see last sale price for all items'),
    ]

    for codename, name in permissions:
        Permission.objects.get_or_create(
            codename=codename,
            name=name,
            content_type=content_type
        )


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_profit_reports_permissions'),
    ]

    operations = [
        migrations.RunPython(add_stock_reports_permissions_version2),
    ]
