# Generated by Django 6.0 on 2026-03-17 11:32

from django.db import migrations


def add_accounts_reports_permissions_version2(apps, schema_editor):
    from django.contrib.auth.models import Permission
    from django.contrib.contenttypes.models import ContentType

    content_type, _ = ContentType.objects.get_or_create(app_label='auth', model='user')

    permissions = [
        ('view_cash_ledger', 'Can view cash detailed ledger'),
        ('view_full_party_balance', 'Can view full party balance'),
        ('view_receivable', 'Can view accounts receivable'),
        ('view_payable', 'Can view accounts payable'),
    ]

    for codename, name in permissions:
        Permission.objects.get_or_create(
            codename=codename,
            name=name,
            content_type=content_type
        )



class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_add_stock_reports_permissions_version2'),
    ]

    operations = [
        migrations.RunPython(add_accounts_reports_permissions_version2),
    ]
