# Generated by Django 6.0 on 2026-03-25 12:22

from django.db import migrations


def add_stock_reports_permissions_version3(apps, schema_editor):
    from django.contrib.auth.models import Permission
    from django.contrib.contenttypes.models import ContentType

    content_type, _ = ContentType.objects.get_or_create(app_label='auth', model='user')

    permissions = [
        ('view_serial_ledger_purchase_only', 'Can view serial ledger for purchase only'),
        ('view_serial_ledger_sale_only', 'Can view serial ledger for sale only'),
    ]

    for codename, name in permissions:
        Permission.objects.get_or_create(
            codename=codename,
            name=name,
            content_type=content_type
        )



class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_add_account_reports_permissions_version2'),
    ]

    operations = [
        migrations.RunPython(add_stock_reports_permissions_version3),
    ]
