# Generated by Django 6.0 on 2026-04-25 13:26

from django.db import migrations

def add_stock_dashboard_options_permissions(apps, schema_editor):
    from django.contrib.auth.models import Permission
    from django.contrib.contenttypes.models import ContentType

    content_type, _ = ContentType.objects.get_or_create(app_label='auth', model='user')

    permissions = [
        ('view_dash_sales_profit', 'Can view dashboard sales & profit section'),
        ('view_dash_stock_overview', 'Can view dashboard stock overview section'),
        ('view_dash_top_parties', 'Can view dashboard top customers & vendors'),
        ('view_dash_receivables_aging', 'Can view dashboard receivables aging'),
        ('view_dash_recent_transactions', 'Can view dashboard recent transactions'),
        ('view_dash_expense_tracking', 'Can view dashboard expense tracking'),
        ('view_dash_smart_alerts', 'Can view dashboard smart alerts'),
    ]

    for codename, name in permissions:
        Permission.objects.get_or_create(
            codename=codename,
            name=name,
            content_type=content_type
        )


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_add_stock_reports_permissions_version3'),
    ]

    operations = [
        migrations.RunPython(add_stock_dashboard_options_permissions),
    ]
